function verifyAdminCode() {
    var code = document.getElementById('codeInput').value;
    //In future the admin code will be generated by the software owner and stored and shared by the owner,
    //The database will save a unique hash of the code, and when the admin enters the code,
    //it will be hashed and compared to the stored hash for verification.
    // For demonstration, we'll just check if it's a specific value
    if (code === 'adminPriv') {
        alert('Code verified! Redirecting to dashboard...');
        document.getElementById('confirmationCode').style.display = 'none';
        return true; // Allow form submission
    } else {
        alert('Warning: Incorrect code. Access denied.');
        window.location.href = 'login.html'; // Redirect to standard login page
        return false; // Prevent form submission
    }

    document.getElementById("adminLoginForm").addEventListener("submit", function(e) {
    if (!verifyAdminCode()) {
        e.preventDefault(); // stop form submission
    }
});
}